---
- name: "Create user {{ item.name }}"
  user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    groups: "{{ item.groups }}"
    append: "yes"

- name: "Add ssh keys for {{ item.name }}"
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ sshkey }}"
  loop: "{{ item.ssh_keys }}"
  loop_control:
    loop_var: sshkey

- name: check that password expired is disable
  command: chage -M 99999 "{{ item.name }}"
  changed_when: false
